CodeErrors = {
            0:  "Task_id: '{0}' with error in property '{1}': {2}",
            1:  "Task '{0}' execution error: {1}",
            2:  "Task '{0}' running",
            3:  "Task '{0}' scheduled",
            4:  "Task '{0}' waiting",
            5:  "Task '{0}' success",
            6:  "Task '{0}' failed",
            7:  "Cycle if add edge from '{0}' to '{1}'",
            8:  "task '{0}' does not belong to DAG",
            9:  "Error processing bq query: {0}",
            10: "Formatting script: {0}",
            11: "{0} engine detected",
            12: "Script from key cache: {0}",
            13: "exceptions.GoogleCloudError: {0}",
            14: "Error processing IAC script: {0}",
            15: "Error processing DP script: {0}:{1}" ,
            16: "Script {0} finished successfully: {1}",
            17: "Submitting script {0} to clsuter {1} Dataproc",
            18: "Dag success with results: {0}"
    }